// Central dummy data for screenshots & UI development
// Toggle with VITE_USE_DUMMY_DATA env var. Defaults to true for screenshot purposes.
export const USE_DUMMY_DATA = import.meta.env.VITE_USE_DUMMY_DATA !== "false";

export const dummyUser = {
  _id: "user_dummy_001",
  fullname: "Aarav Sharma",
  email: "aarav.sharma@example.com",
  phoneNumber: "9876543210",
  role: "Student",
  profile: {
    bio: "Full Stack Developer | MERN | Passionate about building scalable web apps and clean UI.",
    skills: ["React", "Node.js", "MongoDB", "TailwindCSS", "TypeScript", "Docker"],
    profilePhoto: "https://randomuser.me/api/portraits/men/32.jpg",
    resume: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    resumeOriginalName: "Aarav_Sharma_Resume.pdf",
  },
  createdAt: "2024-02-15T10:30:00.000Z",
};

export const dummyRecruiterUser = {
  _id: "user_dummy_rec_001",
  fullname: "Neha Verma",
  email: "neha.verma@techcorp.com",
  phoneNumber: "9123456780",
  role: "Recruiter",
  profile: {
    bio: "Senior Talent Acquisition @ TechCorp | Helping engineers find dream roles.",
    skills: ["Hiring", "Leadership", "HR"],
    profilePhoto: "https://randomuser.me/api/portraits/women/44.jpg",
    resume: "",
    resumeOriginalName: "",
  },
  createdAt: "2023-11-10T08:00:00.000Z",
};

export const dummyCompanies = [
  {
    _id: "comp_001",
    id: "comp_001",
    name: "Google",
    description: "Organizing the world's information and making it universally accessible.",
    website: "https://google.com",
    location: "Bangalore, India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
    createdAt: "2024-01-12T09:00:00.000Z",
  },
  {
    _id: "comp_002",
    id: "comp_002",
    name: "Microsoft",
    description: "Empowering every person and organization to achieve more.",
    website: "https://microsoft.com",
    location: "Hyderabad, India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg",
    createdAt: "2024-02-20T10:15:00.000Z",
  },
  {
    _id: "comp_003",
    id: "comp_003",
    name: "Amazon",
    description: "Earth's most customer-centric company.",
    website: "https://amazon.com",
    location: "Pune, India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    createdAt: "2024-03-05T11:30:00.000Z",
  },
  {
    _id: "comp_004",
    id: "comp_004",
    name: "Flipkart",
    description: "India's leading e-commerce marketplace.",
    website: "https://flipkart.com",
    location: "Bangalore, India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/54/Flipkart_logo.svg",
    createdAt: "2024-03-18T07:45:00.000Z",
  },
  {
    _id: "comp_005",
    id: "comp_005",
    name: "Infosys",
    description: "Global leader in next-gen digital services and consulting.",
    website: "https://infosys.com",
    location: "Mysore, India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/95/Infosys_logo.svg",
    createdAt: "2024-04-01T08:20:00.000Z",
  },
  {
    _id: "comp_006",
    id: "comp_006",
    name: "TCS",
    description: "Building on belief - Tata Consultancy Services.",
    website: "https://tcs.com",
    location: "Mumbai, India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Tata_Consultancy_Services_old_logo.svg",
    createdAt: "2024-04-22T09:10:00.000Z",
  },
];

export const dummyJobs = [
  {
    _id: "job_001",
    id: "job_001",
    title: "Frontend Developer",
    name: "Google",
    description: "Build responsive, high-performance UI with React & Tailwind. Own features end-to-end, collaborate with design & backend.",
    location: "Bangalore",
    salary: "12",
    experience: "2",
    experienceLevel: "2",
    position: "3",
    jobType: "Full-time",
    company: dummyCompanies[0],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    applications: [{ applicant: "user_dummy_001" }, { applicant: "user_dummy_002" }],
    requirements: ["React", "JavaScript", "TailwindCSS"],
  },
  {
    _id: "job_002",
    id: "job_002",
    title: "Backend Developer",
    name: "Microsoft",
    description: "Design scalable Node.js microservices, optimize DB queries, and ensure 99.9% uptime for millions of users.",
    location: "Hyderabad",
    salary: "18",
    experience: "3",
    experienceLevel: "3",
    position: "2",
    jobType: "Full-time",
    company: dummyCompanies[1],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    applications: [{ applicant: "user_dummy_003" }],
    requirements: ["Node.js", "Express", "MongoDB"],
  },
  {
    _id: "job_003",
    id: "job_003",
    title: "Full Stack Developer",
    name: "Amazon",
    description: "MERN stack wizard wanted! Build seller dashboards, payment flows and real-time analytics.",
    location: "Pune",
    salary: "22",
    experience: "2",
    experienceLevel: "2",
    position: "5",
    jobType: "Full-time",
    company: dummyCompanies[2],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    applications: [],
    requirements: ["MERN", "AWS", "REST APIs"],
  },
  {
    _id: "job_004",
    id: "job_004",
    title: "Data Scientist",
    name: "Flipkart",
    description: "Work on recommendation engines, fraud detection and pricing optimization using Python & ML.",
    location: "Bangalore",
    salary: "25",
    experience: "4",
    experienceLevel: "4",
    position: "2",
    jobType: "Full-time",
    company: dummyCompanies[3],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    applications: [{ applicant: "user_dummy_001" }, { applicant: "user_dummy_004" }, { applicant: "user_dummy_005" }],
    requirements: ["Python", "ML", "SQL"],
  },
  {
    _id: "job_005",
    id: "job_005",
    title: "DevOps Engineer",
    name: "Infosys",
    description: "Automate CI/CD with Docker, K8s & Jenkins. Manage infra on AWS/GCP with Terraform.",
    location: "Mysore",
    salary: "16",
    experience: "3",
    experienceLevel: "3",
    position: "4",
    jobType: "Remote",
    company: dummyCompanies[4],
    createdAt: new Date(Date.now() - 0 * 24 * 60 * 60 * 1000).toISOString(), // today
    applications: [],
    requirements: ["Docker", "Kubernetes", "AWS"],
  },
  {
    _id: "job_006",
    id: "job_006",
    title: "UX/UI Designer",
    name: "TCS",
    description: "Craft delightful user experiences, design systems in Figma, and prototype interactive flows.",
    location: "Mumbai",
    salary: "14",
    experience: "2",
    experienceLevel: "2",
    position: "3",
    jobType: "Full-time",
    company: dummyCompanies[5],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    applications: [{ applicant: "user_dummy_006" }],
    requirements: ["Figma", "Design Systems", "Prototyping"],
  },
  {
    _id: "job_007",
    id: "job_007",
    title: "Mern Developer",
    name: "Google",
    description: "Ship full-stack features fast using Mongo, Express, React, Node. GraphQL bonus.",
    location: "Remote",
    salary: "20",
    experience: "1",
    experienceLevel: "1",
    position: "6",
    jobType: "Remote",
    company: dummyCompanies[0],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    applications: [],
    requirements: ["MERN", "GraphQL"],
  },
  {
    _id: "job_008",
    id: "job_008",
    title: "Machine Learning Engineer",
    name: "Microsoft",
    description: "Deploy ML models to production, work with PyTorch/TensorFlow and large-scale data pipelines.",
    location: "Hyderabad",
    salary: "28",
    experience: "5",
    experienceLevel: "5",
    position: "1",
    jobType: "Full-time",
    company: dummyCompanies[1],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    applications: [],
    requirements: ["PyTorch", "TensorFlow", "Python"],
  },
  {
    _id: "job_009",
    id: "job_009",
    title: "Product Manager",
    name: "Amazon",
    description: "Define roadmap, prioritize backlog, and launch customer-obsessed products at scale.",
    location: "Delhi",
    salary: "30",
    experience: "4",
    experienceLevel: "4",
    position: "2",
    jobType: "Full-time",
    company: dummyCompanies[2],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    applications: [],
    requirements: ["Roadmapping", "Agile", "Analytics"],
  },
];

export const dummyAppliedJobs = [
  {
    _id: "app_001",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    job: dummyJobs[0],
    applicant: dummyUser._id,
  },
  {
    _id: "app_002",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "accepted",
    job: dummyJobs[3],
    applicant: dummyUser._id,
  },
  {
    _id: "app_003",
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "rejected",
    job: dummyJobs[1],
    applicant: dummyUser._id,
  },
  {
    _id: "app_004",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: "pending",
    job: dummyJobs[5],
    applicant: dummyUser._id,
  },
];

// For Admin -> ApplicantsTable
export const dummyApplicants = {
  _id: "job_001",
  title: "Frontend Developer",
  applications: [
    {
      _id: "appl_001",
      status: "pending",
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      applicant: {
        _id: "cand_001",
        fullname: "Riya Singh",
        email: "riya.singh@example.com",
        phoneNumber: "9876501234",
        createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        profile: {
          resume: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
          resumeOriginalName: "Riya_Singh.pdf",
        },
      },
    },
    {
      _id: "appl_002",
      status: "pending",
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      applicant: {
        _id: "cand_002",
        fullname: "Karan Mehta",
        email: "karan.mehta@example.com",
        phoneNumber: "9123409876",
        createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        profile: {
          resume: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
          resumeOriginalName: "Karan_Mehta.pdf",
        },
      },
    },
    {
      _id: "appl_003",
      status: "accepted",
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      applicant: {
        _id: "cand_003",
        fullname: "Ananya Gupta",
        email: "ananya.gupta@example.com",
        phoneNumber: "9988776655",
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        profile: {
          resume: "",
          resumeOriginalName: "",
        },
      },
    },
    {
      _id: "appl_004",
      status: "rejected",
      createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      applicant: {
        _id: "cand_004",
        fullname: "Vikram Patel",
        email: "vikram.patel@example.com",
        phoneNumber: "9870098700",
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        profile: {
          resume: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
          resumeOriginalName: "Vikram_Patel.pdf",
        },
      },
    },
  ],
};

export const dummySingleJob = {
  ...dummyJobs[0],
  description: "We are looking for a Frontend Developer to join our Bangalore team. You will build pixel-perfect, accessible React interfaces, collaborate with UX designers, optimize performance (Core Web Vitals), and mentor junior devs. Tech: React, TypeScript, Tailwind, Redux, Vite.",
  experienceLevel: 2,
  applications: dummyApplicants.applications.slice(0, 3).map((a) => ({ applicant: a.applicant._id })),
};

export const dummyAdminJobs = dummyJobs.slice(0, 6);
